name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0.8'
         # mongodb-username: supercharge
         # mongodb-password: secret
          mongodb-db: test
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
     
      - name: npm build
        run: |
          npm ci
          npm run build --if-present
          npm start
