name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: node17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
          npm start
